<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Balance after' => 'Баланс кошелька до',
    'Balance before' => 'Баланс кошелька после',
    'ID' => '',
    'Amount' => 'Сумма',
    'Balance' => 'Баланс',
    'Balance of the purse is not enough' => 'Баланс кошелька не достаточен',
    'Comment' => 'Комментарий',
    'Created On' => 'Дата создания',
    'Incoming transaction' => 'Входящая',
    'Outbound transaction' => 'Исходящая',
    'Owner ID' => 'ID владельца',
    'Owner Type' => 'Тип владельца',
    'Partner ID' => 'ID партнера',
    'Partner Type' => 'Тип партнера',
    'Purse' => 'Кошелек',
    'Purse ID' => 'ID кошелька',
    'Purses' => 'Кошельки',
    'Title' => 'Название',
    'Transaction' => 'Транзакция',
    'Transactions' => 'Транзакции',
    'Type' => 'Тип',
    'Updated On' => 'Дата обновления',
];
